/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gt.edu.umg.biblioteca.vista;

import gt.edu.umg.biblioteca.conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author emanu
 */
public class FrmLibro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLibro.class.getName());

    /**
     * Creates new form FrmLibro
     */
    public FrmLibro() {
        initComponents();
        configurarTabla();
        cargarLibros();
        setLocationRelativeTo(null);
    }
    
    private void configurarTabla() {
    DefaultTableModel modelo =
            new DefaultTableModel(
                    new Object[]{
                        "ID",
                        "Titulo",
                        "Autor",
                        "Categoria",
                        "Año",
                        "Editorial"
                    },
                    0
            ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    tblLibros.setModel(modelo);
}
private void cargarLibros() {
    DefaultTableModel modelo =
            (DefaultTableModel) tblLibros.getModel();
    modelo.setRowCount(0);
    String sql =
            "SELECT id, titulo, autor, categoria, anio, editorial "
            + "FROM Libro "
            + "ORDER BY id";
    try (
        Connection cn = Conexion.Conectar();
        PreparedStatement ps = cn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery()
    ) {
        while (rs.next()) {
            Object[] fila = {
                rs.getInt("id"),
                rs.getString("titulo"),
                rs.getString("autor"),
                rs.getString("categoria"),
                rs.getInt("anio"),
                rs.getString("editorial")
            };
            modelo.addRow(fila);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
                this,
                "Error al consultar:\n" + e.getMessage()
        );
    }
}
private void limpiar() {
    txtTitulo.setText("");
    txtAutor.setText("");
    txtCategoria.setText("");
    txtAnio.setText("");
    tblLibros.clearSelection();
    txtTitulo.requestFocus();
    txtEditorial.setText("");
}

private boolean validarCampos() {
    if (txtTitulo.getText().trim().isEmpty()
            || txtAutor.getText().trim().isEmpty()
            || txtCategoria.getText().trim().isEmpty()
            || txtAnio.getText().trim().isEmpty()
            || txtEditorial.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Todos los campos son obligatorios."
        );
        return false;
    }
    try {
        int anio =
                Integer.parseInt(txtAnio.getText().trim());
        if (anio <= 0) {
                        
            JOptionPane.showMessageDialog(
                    this,
                    "El año debe ser válido."
            );
            return false;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(
                this,
                "El año debe ser numérico."
        );
        return false;
    }
    return true;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtEditorial = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRO LIBROS");

        jLabel2.setText("TITULO:");

        jLabel3.setText("AUTOR:");

        jLabel4.setText("CATEGORIA:");

        jLabel5.setText("AÑO:");

        txtCategoria.addActionListener(this::txtCategoriaActionPerformed);

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Titulo", "Autor", "Categoria", "Año", "Editorial"
            }
        ));
        tblLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLibrosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLibros);

        jLabel6.setText("EDITORIAL:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTitulo)
                                    .addComponent(txtAutor)
                                    .addComponent(txtCategoria)
                                    .addComponent(txtAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                    .addComponent(txtEditorial)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(37, 37, 37)
                                .addComponent(btnModificar)
                                .addGap(32, 32, 32)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
            int fila = tblLibros.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(
                this,
                "Seleccione un libro."
        );
        return;
    }
    if (!validarCampos()) {
        return;
    }
    int id =
            Integer.parseInt(tblLibros.getValueAt(fila, 0).toString()
            );
                    
    String titulo = txtTitulo.getText().trim();
    String autor = txtAutor.getText().trim();
    String categoria = txtCategoria.getText().trim();
    int anio =
            Integer.parseInt(
                    txtAnio.getText().trim()
            );
    String editorial = txtEditorial.getText().trim();
    String sql =
            "UPDATE Libro "
            + "SET titulo=?, autor=?, categoria=?, anio=?, editorial=? "
            + "WHERE id=?";
    try (
        Connection cn = Conexion.Conectar();
        PreparedStatement ps = cn.prepareStatement(sql)
    ) {
        ps.setString(1, titulo);
        ps.setString(2, autor);
        ps.setString(3, categoria);
        ps.setInt(4, anio);
        ps.setString(5, editorial);
        ps.setInt(6, id);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(
                this,
                "Libro modificado correctamente."
        );
        cargarLibros();
        limpiar();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
                this,
                "Error al modificar:\n" + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
            if (!validarCampos()) {
        return;
    }
    String titulo = txtTitulo.getText().trim();
    String autor = txtAutor.getText().trim();
    String categoria = txtCategoria.getText().trim();
    int anio =
            Integer.parseInt(
                    txtAnio.getText().trim()
            );
    String editorial = txtEditorial.getText().trim();
    String sql =
            "INSERT INTO Libro "
            + "(titulo, autor, categoria, anio, editorial) "
            + "VALUES (?, ?, ?, ?, ?)";
    try (
        Connection cn = Conexion.Conectar();
        PreparedStatement ps = cn.prepareStatement(sql)
    ) {
        ps.setString(1, titulo);
        ps.setString(2, autor);
        ps.setString(3, categoria);
        ps.setInt(4, anio);
        ps.setString(5, editorial);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(
                this,
                "Libro registrado correctamente."
        );
        cargarLibros();
        limpiar();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
                this,
                "Error al guardar:\n" + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLibrosMouseClicked
        // TODO add your handling code here:
         int fila = tblLibros.getSelectedRow();
    if (fila == -1) {
        return;
    }
    txtTitulo.setText(
            tblLibros.getValueAt(fila, 1).toString()
    );
    txtAutor.setText(
            tblLibros.getValueAt(fila, 2).toString()
    );
    txtCategoria.setText(
            tblLibros.getValueAt(fila, 3).toString()
    );
    txtAnio.setText(
            tblLibros.getValueAt(fila, 4).toString()
    );
    txtEditorial.setText(tblLibros.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_tblLibrosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         int fila = tblLibros.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(
                this,
                "Seleccione un libro."
        );
        return;
    }
    int id =
            Integer.parseInt(tblLibros.getValueAt(fila, 0).toString()
            );
    int respuesta =
                    
            JOptionPane.showConfirmDialog(
                    this,
                    "¿Está seguro de eliminar este libro?",
                    "Confirmación",
                    JOptionPane.YES_NO_OPTION
            );
    if (respuesta != JOptionPane.YES_OPTION) {
        return;
    }
    String sql =
            "DELETE FROM Libro WHERE id=?";
    try (
        Connection cn = Conexion.Conectar();
        PreparedStatement ps = cn.prepareStatement(sql)
    ) {
        ps.setInt(1, id);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(
                this,
                "Libro eliminado correctamente."
        );
        cargarLibros();
        limpiar();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
                this,
                "Error al eliminar:\n" + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLibro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
